<a href="https://colab.research.google.com/github/345bc/th-deep-learning/blob/main/th_tuan01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nội dung numpy

tạo array 1 chiều

In [ ]:
import numpy

my_list=[1,2,3,4]
print('list', my_list)

my_numpy_array = numpy.array(my_list)
print('numpy array', my_numpy_array)

tạo array 2 chiều



In [ ]:
import numpy
'''mang 2 chieu'''
c = numpy.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

tạo array 3 chiều

In [ ]:
import numpy
'''mang 3 chieu'''
c= numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)
print(c.dtype)


Tạo Array với giá trị ban đầu là 0 hoặc 1


In [ ]:
import numpy
c=numpy.zeros((2,2))
d=numpy.ones((2,3))
print('zero: \n',c)
print('one: \n',d)

Reshape thay đổi kích thước ma trận


In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape,"\n")

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)


Platten là chuyển array nhiều chiều về 1 chiều

In [ ]:
import numpy as np
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
a=e.flatten()
print('flatten a:\n',a)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
b=g.flatten()
print('flatten b:\n',b)

Thêm dòng dữ liệu với hstack và vstack

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.hstack((a,b))
print(c)
d=np.vstack((a,b))
print(d)


Sinh mảng số nguyên ngẫu nhiên


In [ ]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Sinh mảng số thực trong khoảng [0, 1]


In [5]:
import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.53538054 0.51398499 0.90726798 0.30851171 0.48562741]
Random 2-D array
 [[0.0763039  0.3282978  0.67594662 0.13104698]
 [0.20037173 0.27504127 0.32588396 0.13265887]
 [0.7096932  0.76987921 0.78092839 0.547647  ]]
Random 3-D array
 [[[0.34971779 0.64817134 0.50752119]
  [0.91908094 0.17290449 0.33047404]
  [0.91157495 0.06830096 0.04221498]
  [0.18702769 0.59023532 0.91675413]]

 [[0.36574597 0.17259434 0.8553287 ]
  [0.81235226 0.89361131 0.0268164 ]
  [0.55168463 0.81926095 0.46515316]
  [0.83395267 0.0863282  0.40982476]]

 [[0.28685187 0.9115685  0.92914811]
  [0.51868092 0.31461699 0.67704995]
  [0.10376729 0.59436308 0.54119536]
  [0.74138597 0.37992829 0.07421522]]]


# Tensor


In [8]:
import tensorflow as tf

tensor 0 chiều

In [7]:

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


tensor 1 chiều

In [10]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


tensor 2 chiều

In [11]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


tensor 3 chiều


In [14]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)



tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


tensor gán giá trị 0 ban đầu

In [15]:
t_zero = tf.zeros(10)
print(t_zero)
a_zero=tf.zeros([2,2])
print(a_zero)
b_zero=tf.zeros([2,2,3])
print(b_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


tensor gán giá trị 1 ban đầu

In [16]:
t_ones = tf.ones(10)
print(t_ones)
a_ones=tf.ones([2,2])
print(a_ones)
b_ones=tf.ones([2,2,3])
print(b_ones)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)
