<a href="https://colab.research.google.com/github/345bc/th-deep-learning/blob/main/th_tuan01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nội dung numpy

tạo array 1 chiều

In [1]:
import numpy

my_list=[1,2,3,4]
print('list', my_list)

my_numpy_array = numpy.array(my_list)
print('numpy array', my_numpy_array)

list [1, 2, 3, 4]
numpy array [1 2 3 4]


tạo array 2 chiều



In [2]:
import numpy
'''mang 2 chieu'''
c = numpy.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


tạo array 3 chiều

In [3]:
import numpy
'''mang 3 chieu'''
c= numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)
print(c.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
int64


Tạo Array với giá trị ban đầu là 0 hoặc 1


In [4]:
import numpy
c=numpy.zeros((2,2))
d=numpy.ones((2,3))
print('zero: \n',c)
print('one: \n',d)

zero: 
 [[0. 0.]
 [0. 0.]]
one: 
 [[1. 1. 1.]
 [1. 1. 1.]]


Reshape thay đổi kích thước ma trận


In [5]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape,"\n")

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3) 

reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


Platten là chuyển array nhiều chiều về 1 chiều

In [6]:
import numpy as np
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
a=e.flatten()
print('flatten a:\n',a)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
b=g.flatten()
print('flatten b:\n',b)

[[1. 2. 3.]
 [4. 5. 6.]]
flatten a:
 [1. 2. 3. 4. 5. 6.]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
flatten b:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dòng dữ liệu với hstack và vstack

In [7]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.hstack((a,b))
print(c)
d=np.vstack((a,b))
print(d)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Sinh mảng số nguyên ngẫu nhiên


In [8]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [48  4  3 98 14]
Random 2-D array
 [[18 37 61 10]
 [19 18  3 70]
 [91 77 80 90]]
Random 3-D array
 [[[98 94 53]
  [35 34 30]
  [60 23 44]
  [67 19  6]]

 [[ 9 96 57]
  [52 62 81]
  [32 56 89]
  [86  1 55]]

 [[22 59 84]
  [50 40 18]
  [33 58 36]
  [14 34 91]]]


Sinh mảng số thực trong khoảng [0, 1]


In [9]:
import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.93791347 0.49510596 0.68436238 0.74055838 0.95194045]
Random 2-D array
 [[0.90858526 0.33014686 0.25585841 0.02944046]
 [0.09594101 0.1646412  0.61318954 0.43286018]
 [0.90894234 0.97154838 0.11383605 0.16307293]]
Random 3-D array
 [[[0.88441165 0.00962152 0.05090127]
  [0.05072381 0.95087951 0.68546918]
  [0.71394209 0.85408861 0.73251674]
  [0.3562476  0.10571894 0.18636354]]

 [[0.75209762 0.69253971 0.8341062 ]
  [0.46302794 0.81576283 0.74497057]
  [0.195726   0.20924451 0.91837842]
  [0.83006383 0.83286687 0.5146453 ]]

 [[0.85759128 0.66368667 0.39811129]
  [0.43769383 0.06966498 0.90701045]
  [0.40106022 0.36670891 0.06978791]
  [0.94220447 0.31998787 0.32246066]]]


# Tensor


In [10]:
import tensorflow as tf

tensor 0 chiều

In [11]:

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [12]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


tensor 1 chiều

In [13]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


tensor 2 chiều

In [14]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


tensor 3 chiều


In [15]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)



tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


tensor gán giá trị 0 ban đầu

In [16]:
t_zero = tf.zeros(10)
print(t_zero)
a_zero=tf.zeros([2,2])
print(a_zero)
b_zero=tf.zeros([2,2,3])
print(b_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


tensor gán giá trị 1 ban đầu

In [17]:
t_ones = tf.ones(10)
print(t_ones)
a_ones=tf.ones([2,2])
print(a_ones)
b_ones=tf.ones([2,2,3])
print(b_ones)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)
