<a href="https://colab.research.google.com/github/345bc/th-deep-learning/blob/main/th_tuan01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nội dung numpy

tạo array 1 chiều

In [15]:
import numpy

my_list=[1,2,3,4]
print('list', my_list)

my_numpy_array = numpy.array(my_list)
print('numpy array', my_numpy_array)

list [1, 2, 3, 4]
numpy array [1 2 3 4]


tạo array 2 chiều



In [16]:
import numpy
'''mang 2 chieu'''
c = numpy.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


tạo array 3 chiều

In [17]:
import numpy
'''mang 3 chieu'''
c= numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.shape)
print(c.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
int64


Tạo Array với giá trị ban đầu là 0 hoặc 1


In [18]:
import numpy
c=numpy.zeros((2,2))
d=numpy.ones((2,3))
print('zero: \n',c)
print('one: \n',d)

zero: 
 [[0. 0.]
 [0. 0.]]
one: 
 [[1. 1. 1.]
 [1. 1. 1.]]


Reshape thay đổi kích thước ma trận


In [19]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
print(g.shape,"\n")

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3) 

reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


Platten là chuyển array nhiều chiều về 1 chiều

In [20]:
import numpy as np
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
a=e.flatten()
print('flatten a:\n',a)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
])
print(g)
b=g.flatten()
print('flatten b:\n',b)

[[1. 2. 3.]
 [4. 5. 6.]]
flatten a:
 [1. 2. 3. 4. 5. 6.]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
flatten b:
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


Thêm dòng dữ liệu với hstack và vstack

In [21]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.hstack((a,b))
print(c)
d=np.vstack((a,b))
print(d)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Sinh mảng số nguyên ngẫu nhiên


In [22]:
a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [17 25 33 79 12]
Random 2-D array
 [[39 36 43 60]
 [30 23 12 39]
 [37 50 17 47]]
Random 3-D array
 [[[14 67 94]
  [ 7 14 98]
  [34 80  3]
  [71 39 20]]

 [[42 82 71]
  [90 52 87]
  [70 90 99]
  [74 61 37]]

 [[19 24 81]
  [23 45 26]
  [20 38 85]
  [ 4 16  4]]]


Sinh mảng số thực trong khoảng [0, 1]


In [23]:
import numpy as np

In [24]:


a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.62982049 0.96991845 0.5325223  0.41928718 0.04745192]
Random 2-D array
 [[0.09635177 0.80427221 0.74695698 0.46863521]
 [0.38654171 0.32547198 0.45640002 0.32947777]
 [0.78759499 0.69071223 0.89313067 0.52891606]]
Random 3-D array
 [[[0.25407369 0.12798815 0.94895999]
  [0.04889654 0.09989307 0.40951632]
  [0.07623191 0.0268871  0.19310152]
  [0.44287873 0.80645481 0.16304124]]

 [[0.86851025 0.4267402  0.17691722]
  [0.46028448 0.0022183  0.65391109]
  [0.03665201 0.36096884 0.26975406]
  [0.36933093 0.110865   0.31792577]]

 [[0.71345833 0.5678861  0.03224381]
  [0.55728621 0.80429984 0.43215319]
  [0.67288077 0.81997027 0.58253819]
  [0.41902003 0.63775587 0.58160153]]]


Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian


In [25]:
a=np.random.normal(5)
print(a)

4.034467952157135


Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước


In [26]:
#sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

#sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

6
[[20 20  6  4  2]
 [ 8 18 20 18  2]
 [12 12 10 20 16]]


Thay đổi giá trị của ma trận


In [27]:
#Tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
np.array(A)[2] = 2
print('Change values of third row with array\n', A)
np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Sinh dãy số theo khoảng cho trước




- Dùng hàm arange

In [28]:
#tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)

#tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


- Dùng hàm Linspace

In [29]:
a= np.linspace(1.,5.,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Index và slice

In [30]:
# slice

a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)

print('first row:', a[0])
print('second row:', a[1])

# indexing
print('Second column:', a[:, 1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column [1 4]
First two values of second row: [4 5]


#Pandas

Cấu trúc dữ liệu 1 chiều series

In [31]:
# Tạo pandas series từ list
import pandas as pd

a = pd.Series([1., 2., 3.])
print(a)

print('First value: ', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)

print('First value: ', b['a'])

# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)
print(myvar)


0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value:  1.0
day1    420
day2    380
day3    390
dtype: int64


Tạo đối tượng dataframe


- Chuyển đổi từ numpy -> pandas và ngược lại

In [32]:

# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)

print('DataFrame:\n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)

print('Numpy array:\n', numpy_h)


DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


- Dataframe 2 chiều có tên và cột

In [41]:

dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}

df_dic = pd.DataFrame(dic)

print(df_dic)


    Name  Age
0   John   30
1  Smith   40


In [42]:

# tạo mảng 20 x 4
r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

print(df.head())  # in 5 dòng đầu tiên


        so1       so2       so3       so4
0 -0.760281  0.124208  0.060415 -0.024656
1  0.300764 -0.623806  2.520442 -0.772520
2 -0.709601  0.436071  0.307628 -0.228375
3  1.293803  0.584906 -0.094158 -0.042358
4  2.331634  1.213472  0.810194 -1.381230


- Slice dataframe

In [43]:

# tạo mảng 20 x 4
r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  # in 5 dòng đầu tiên

# chọn 1 cột
print('Chọn cột so1\n', df['so1'])

# chọn nhiều dòng
print('Chọn nhiều dòng\n', df[0:3])

# chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])

# chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])

# Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)


        so1       so2       so3       so4
0  0.371036 -0.811028 -0.591423  0.690749
1 -0.870143 -0.971775 -0.447259 -0.023977
2  1.228729 -1.177694  0.523482  0.192256
3  1.001453 -0.741591 -0.683475  0.588084
4  0.645684  0.667870  0.071157  1.965653
Chọn cột so1
 0     0.371036
1    -0.870143
2     1.228729
3     1.001453
4     0.645684
5     0.490633
6     0.264392
7    -0.785453
8    -1.628963
9     1.040665
10    1.960993
11    1.643257
12   -0.586049
13   -0.984477
14    1.001860
15   -1.191676
16   -0.284473
17   -0.216398
18   -0.764375
19    0.188289
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  0.371036 -0.811028 -0.591423  0.690749
1 -0.870143 -0.971775 -0.447259 -0.023977
2  1.228729 -1.177694  0.523482  0.192256
Chọn nhiều cột
          so1       so3
0   0.371036 -0.591423
1  -0.870143 -0.447259
2   1.228729  0.523482
3   1.001453 -0.683475
4   0.645684  0.071157
5   0.490633  0.586604
6   0.264392  0.031836
7  -0.785453  0.781033


Nối nhiều DataFrame

In [45]:
# Nối 2 DataFrame
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))

# Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


Đọc dữ liệu từ csv

In [52]:
from google.colab import files
uploaded = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv


In [50]:
# Đọc dữ liệu từ CSV
path = '/content/Salary_Data.csv'

COLUMNS = ['YearsExperience', 'Salary']

df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)

df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

   YearsExperience  Salary
0  YearsExperience  Salary
1              1.1   39343
2              1.3   46205
3              1.5   37731
4              2.0   43525
(21, 2)
   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
(20, 2)


Gom nhóm dữ liệu DataFrame

In [57]:

# Gom nhóm dữ liệu trong DataFrame
path = '/content/hotel_bookings.csv'

df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)

print(df_csv.head())

# sửa df → df_csv
print(df_csv.groupby('hotel')['is_canceled'].mean())

print(df_csv.groupby('hotel')['adr'].mean())




          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1     

#Bài tập numpy và pandas

 Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5


In [58]:

arr = np.array([1]*10 + [0]*10 + [5]*10)

print(arr)


[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]


Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên

In [59]:

# tạo DataFrame 4x3 ngẫu nhiên
data = np.random.randn(4, 3)

df = pd.DataFrame(data, columns=['A', 'B', 'C'])

print("DataFrame ban đầu:\n", df)

# sắp xếp theo cột A
df_sorted = df.sort_values(by='A')

print("\nDataFrame sau khi sắp xếp theo cột A:\n", df_sorted)


DataFrame ban đầu:
           A         B         C
0  1.415586 -0.144695  1.358394
1  0.840778 -0.003027  0.699762
2  0.255298  1.214931 -2.160022
3  0.522176  0.805255  0.404257

DataFrame sau khi sắp xếp theo cột A:
           A         B         C
2  0.255298  1.214931 -2.160022
3  0.522176  0.805255  0.404257
1  0.840778 -0.003027  0.699762
0  1.415586 -0.144695  1.358394


# Tensor


In [33]:
import tensorflow as tf

tensor 0 chiều

In [34]:

rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [35]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


tensor 1 chiều

In [36]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


tensor 2 chiều

In [37]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


tensor 3 chiều


In [38]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)



tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


tensor gán giá trị 0 ban đầu

In [39]:
t_zero = tf.zeros(10)
print(t_zero)
a_zero=tf.zeros([2,2])
print(a_zero)
b_zero=tf.zeros([2,2,3])
print(b_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


tensor gán giá trị 1 ban đầu

In [40]:
t_ones = tf.ones(10)
print(t_ones)
a_ones=tf.ones([2,2])
print(a_ones)
b_ones=tf.ones([2,2,3])
print(b_ones)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


Tạo tensor tự động với giá trị bất kỳ

In [60]:
t_1 = tf.fill((3,), 10)
print(t_1)

t_2 = tf.fill((3, 3), 9)
print(t_2)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


Tạo Tensor 1 chiều với hàm linspace

In [61]:

lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)


tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


Tạo Tensor 1 chiều với hàm range

In [62]:

range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)


tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [63]:

range_tensor = tf.range(3.0, delta=0.5)
print(range_tensor)


tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


 Tạo tensor với giá trị ngẫu nhiên

In [64]:
#với hàm random.normal
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor = tf.random.normal([3, 3])
print(range_tensor)

tf.Tensor([ 0.15889055  0.25255185 -0.2851703   1.4112705   0.56339616], shape=(5,), dtype=float32)
tf.Tensor(
[[-1.2700663   0.8193615   0.8887299 ]
 [ 0.72127783  1.948563    0.9452972 ]
 [ 0.03026155 -1.849649   -0.08922809]], shape=(3, 3), dtype=float32)


In [66]:
#với hàm random.truncated_normal
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

tf.Tensor([ 0.32194668  0.7473243   0.4099861   0.49139038 -0.9896074 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 1.0364337   1.0123581 ]
 [ 0.13235773 -0.9354712 ]
 [-0.50823003 -0.70255595]], shape=(3, 2), dtype=float32)


In [82]:
#với hàm random.uniform
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)


range_tensor = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor)

range_tensor = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor)


tf.Tensor([17.413677 16.285461 10.173846 13.431449 15.106377], shape=(5,), dtype=float32)
tf.Tensor(
[[17.402308 13.39382 ]
 [15.692506 14.481139]
 [12.928551 14.260056]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[18.031559  14.977774  13.705404  19.118673  16.37642  ]
  [11.82097   16.379196  12.770147  10.422711  18.421938 ]]

 [[19.06372   12.22556   19.198462  16.878908  14.270517 ]
  [18.78158   16.943958  14.656759  15.292577  13.301902 ]]

 [[11.275486  11.615352  15.085136  14.430178  13.520588 ]
  [18.969147  12.4940815 17.632832  18.593578  10.848016 ]]], shape=(3, 2, 5), dtype=float32)


In [84]:
#với shuffle để xáo trộn gia trị tong tensor

range_tensor = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor)

print(tf.random.shuffle(range_tensor))


tf.Tensor(
[[[11.424145  14.016162  13.336019  16.816542  16.908703 ]
  [12.206942  16.13362   19.588974  13.314948  12.809678 ]]

 [[15.807008  11.739465  19.826159  19.146084  17.685434 ]
  [12.626563  19.006527  19.757214  16.445093  13.313885 ]]

 [[17.758438  10.226974  12.002098  14.916965  12.457867 ]
  [18.612217  10.3907385 13.492657  13.18609   19.203915 ]]], shape=(3, 2, 5), dtype=float32)
tf.Tensor(
[[[17.758438  10.226974  12.002098  14.916965  12.457867 ]
  [18.612217  10.3907385 13.492657  13.18609   19.203915 ]]

 [[15.807008  11.739465  19.826159  19.146084  17.685434 ]
  [12.626563  19.006527  19.757214  16.445093  13.313885 ]]

 [[11.424145  14.016162  13.336019  16.816542  16.908703 ]
  [12.206942  16.13362   19.588974  13.314948  12.809678 ]]], shape=(3, 2, 5), dtype=float32)


Chuyển đổi kiểu dữ liệu

In [85]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)


tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


Các phép toán trong tensoflow


- Tính căn bậc 2 của một tensor scalar

In [86]:
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))


tf.Tensor(1.4142135, shape=(), dtype=float32)


- Cộng 2 tensor

In [87]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.add(a, b)
d = a + b

print(c)
print(d)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


- Nhân 2 tensor

In [88]:
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.multiply(a, b)
d = a * b

print(c)
print(d)

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


- Tổng hợp

In [89]:
a = tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(i)
print(l)

tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


Các phép toán làm tròn và so sánh

In [90]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


Các phép toán trên vector và ma trận

In [91]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])

t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])

t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)

d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


Biến trong tensorflow

In [92]:
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

print('Shape:', diem.shape)
print('Dtype:', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape: (2,)
Dtype: <dtype: 'int32'>
numpy: [5 9]


In [93]:
#Phép gán giá trị cho tensor
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

diem.assign([8, 10])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>


## Bài tập

Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [95]:

tensor = tf.zeros([2, 3])

print(tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng,
trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.

In [96]:

# 1. Tạo tensor ngẫu nhiên
x = tf.random.uniform((3, 2, 2))
y = tf.random.uniform((3, 2, 2))

# 2. Hàm toán học (Python bình thường)

def add_func(x, y):
    return x + y

def sub_func(x, y):
    return x - y

def mul_func(x, y):
    return x * y

def div_func(x, y):
    return x / y

# 3. Chuyển sang TensorFlow graph
add_graph = tf.function(add_func)
sub_graph = tf.function(sub_func)
mul_graph = tf.function(mul_func)
div_graph = tf.function(div_func)

# 4. Gọi hàm

print("Addition:\n", add_graph(x, y))
print("\nSubtraction:\n", sub_graph(x, y))
print("\nMultiplication:\n", mul_graph(x, y))
print("\nDivision:\n", div_graph(x, y))

Addition:
 tf.Tensor(
[[[0.70273995 1.0613072 ]
  [1.1194569  0.15569699]]

 [[1.196301   1.3336005 ]
  [0.9792247  1.2281916 ]]

 [[1.5655564  1.6703418 ]
  [0.5960083  1.4655547 ]]], shape=(3, 2, 2), dtype=float32)

Subtraction:
 tf.Tensor(
[[[-0.4471345   0.66329527]
  [-0.28819096  0.04487646]]

 [[ 0.01937199  0.24744296]
  [-0.85785794  0.48530126]]

 [[-0.12553108 -0.31025517]
  [ 0.0400064   0.36548233]]], shape=(3, 2, 2), dtype=float32)

Multiplication:
 tf.Tensor(
[[[0.07347855 0.17160308]
  [0.2925324  0.00555691]]

 [[0.3576902  0.4293156 ]
  [0.05574018 0.31823432]]

 [[0.6088022  0.6734459 ]
  [0.08840635 0.50356835]]], shape=(3, 2, 2), dtype=float32)

Division:
 tf.Tensor(
[[[0.22228989 4.333042  ]
  [0.5905354  1.8098942 ]]

 [[1.0329195  1.45563   ]
  [0.06606493 2.306522  ]]

 [[0.85153806 0.6867054 ]
  [1.1439074  1.6644696 ]]], shape=(3, 2, 2), dtype=float32)
